# Generated by Django 3.2.7 on 2021-09-12 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(help_text='Ingrese su nombre Completo', max_length=50, verbose_name='Nombre:')),
                ('apellidos', models.CharField(help_text='Ingrese sus Apellidos', max_length=50, verbose_name='Apellidos:')),
                ('nit', models.CharField(help_text='Ingrese Nit', max_length=100, verbose_name='Nit:')),
                ('fechanacimiento', models.DateField(blank=True, help_text='Ingrese Fecha de Nacimiento', null=True, verbose_name='Fecha de Nacimiento')),
                ('cui', models.BigIntegerField(blank=True, help_text='Ingrese Numero De Identificación Personal', null=True, verbose_name='DPI/CUI:')),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', help_text='Selección de Género', max_length=1, verbose_name='Genero:')),
                ('direccion', models.CharField(help_text='Ingrese Dirección', max_length=100, verbose_name='Dirección:')),
                ('email', models.CharField(blank=True, help_text='Ingrese el correo electronico que utiliza', max_length=50, null=True, verbose_name='Email:')),
                ('telefono', models.BigIntegerField(help_text='Ingrese un número de telefono de casa', verbose_name='Telefono de Casa:')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('tipo', models.CharField(choices=[('E', 'Empresa'), ('I', 'Individual')], default='I', help_text='Selección de tipo de cliente', max_length=1, verbose_name='Tipo de Cliente:')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Movil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Marca', models.CharField(help_text='Ingrese la Marca', max_length=50, verbose_name='Marca:')),
                ('modelo', models.CharField(help_text='Ingrese el modelo', max_length=50, verbose_name='Modelo:')),
                ('imei', models.CharField(help_text='Ingrese el IMEI (BAJO LA BATERIA O EN CONFIGURACIÓN', max_length=50, verbose_name='Imei:')),
                ('ano', models.DateField()),
                ('color', models.CharField(help_text='Ingrese el color', max_length=50, verbose_name='Color:')),
                ('observaciones', models.TextField(help_text='Ingrese la observacion', max_length=500, verbose_name='Observaciones:')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.cliente')),
            ],
            options={
                'verbose_name': 'Móvil',
                'verbose_name_plural': 'Móviles',
            },
        ),
        migrations.CreateModel(
            name='Repuestos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ingrese el nombre', max_length=50, verbose_name='Nombre:')),
                ('Marca', models.CharField(help_text='Ingrese la Marca', max_length=50, verbose_name='Marca:')),
                ('Price', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Précio')),
                ('cantidad', models.FloatField(verbose_name='Existéncia')),
                ('observaciones', models.TextField(help_text='Ingrese la observacion', max_length=500, verbose_name='Observaciones:')),
            ],
            options={
                'verbose_name': 'Repuesto',
                'verbose_name_plural': 'Repuestos',
            },
        ),
        migrations.CreateModel(
            name='Tenico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(help_text='Ingrese su nombre Completo', max_length=50, verbose_name='Nombre:')),
                ('apellidos', models.CharField(help_text='Ingrese sus Apellidos', max_length=50, verbose_name='Apellidos:')),
                ('nit', models.CharField(help_text='Ingrese Nit', max_length=100, verbose_name='Nit:')),
                ('fechanacimiento', models.DateField(blank=True, help_text='Ingrese Fecha de Nacimiento', null=True, verbose_name='Fecha de Nacimiento')),
                ('cui', models.BigIntegerField(blank=True, help_text='Ingrese Numero De Identificación Personal', null=True, verbose_name='DPI/CUI:')),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', help_text='Selección de Género', max_length=1, verbose_name='Genero:')),
                ('direccion', models.CharField(help_text='Ingrese Dirección', max_length=100, verbose_name='Dirección:')),
                ('email', models.CharField(blank=True, help_text='Ingrese el correo electronico que utiliza', max_length=50, null=True, verbose_name='Email:')),
                ('telefono', models.BigIntegerField(help_text='Ingrese un número de telefono de casa', verbose_name='Telefono de Casa:')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('fechacontra', models.DateField(blank=True, help_text='Ingrese Fecha de Contratación', null=True, verbose_name='Fecha de Contratación')),
            ],
            options={
                'verbose_name': 'Técnico',
                'verbose_name_plural': 'Técnicos',
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('R', 'Reparación'), ('C', 'Remplazo'), ('M', 'Mantenimiento'), ('S', 'Software')], default='R', help_text='Selección de Servicio', max_length=1, verbose_name='Tipo de Servicio:')),
                ('movil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.movil')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
            },
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechadiag', models.DateField(blank=True, help_text='Ingrese Fecha de Contratación', null=True, verbose_name='Fecha de Contratación')),
                ('descripcion', models.TextField(help_text='Ingrese la Descripción', max_length=500, verbose_name='Descripción:')),
                ('tecnico_diag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.tenico')),
            ],
            options={
                'verbose_name': 'Móvil',
                'verbose_name_plural': 'Móviles',
            },
        ),
    ]
