# Generated by Django 3.2.7 on 2021-09-15 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_auto_20210912_1310'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('total', models.FloatField(blank=True, null=True, verbose_name='Total')),
                ('diag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.diagnostico')),
                ('repues', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.repuestos')),
            ],
            options={
                'verbose_name': 'Facturación',
                'verbose_name_plural': 'Facturaciones',
            },
        ),
        migrations.CreateModel(
            name='FacturaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Cantidad')),
                ('subtotal', models.FloatField()),
                ('fac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='apps.factura')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.repuestos')),
            ],
            options={
                'verbose_name': 'Detalle de Factura',
                'verbose_name_plural': 'Detalles de Facturas',
            },
        ),
    ]
