# Generated by Django 3.2.7 on 2021-09-15 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_factura_facturadetalle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='repues',
        ),
    ]
